spring:
  application:
     name: employee-service     

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}    
    
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka
      
server:
  port: 0 
  
logging:
  level: 
    httpclient.wire: DEBUG 
    
pivotal:
  adminservice:
    name: admin-service
  loginservice:
    name: login-service
  assessmentservice:
    name: assessment-service
  employeeservice:
    name: employee-service    

  
 
 
  